### ISSUE TITLE
Width constraint blocks Close button

### ISSUE THREAD

**Issue by iotech-fvtt** [giffyglyph/foundry_5e_monster_maker#12]
I have several modules that add items to the Actor window header (DAE, GM Notes, Translate, Popout, PaperDoll, etc.) The resizing handle only allows vertical adjustment of the window size, so I cant make it wider to expose the Close button. 
Please remove the width adjustment constraint or make it toggleable in Module Settings.

Edit: It also blocks the Sheet link, or I could just change it to another sheet then close it. 

![Giffy](https://user-images.githubusercontent.com/29070865/120238805-33448980-c21a-11eb-9ac4-3f1968079863.png)

**Comment by giffyglyph** [comment]
Buttons now wrap correctly in the window header. Verified in v0.5.5-dev; closing.
