### ISSUE TITLE
Inititative not being rolled correctly

### ISSUE THREAD

**Issue by Wigsinator** [giffyglyph/foundry_5e_monster_maker#14]
When rolling for initiative, an error is produced: Error: A Die term must have a numeric number of faces.

This is caused by setting actorData.attributes.init.mod to the string representation of that modifier.

Additionally, none of the other values are applied because they are being set to value and total, neither of which are included in the basic initiative formula. This can be corrected by replacing lines 101-104 with

`actorData.attributes.init.bonus = monsterData.initiative.value;`

**Comment by giffyglyph** [comment]
Tested and verified in v0.5.4-dev. Closing.
