### ISSUE TITLE
Prototype Token Image update does not work

### ISSUE THREAD

**Issue by g-bauer** [giffyglyph/foundry_5e_monster_maker#2]
May be this is intended or simply not yet implemented, but currently changes to `Prototype Token` > `Image` are not applied.
This prohibits usage of the `Randomize Wildcard Images`.

Changes such as `Scale` work for a `Token` (actor on the canvas).

**Comment by giffyglyph** [comment]
I think this has been resolved as-of v0.5.0 so will close—please reopen if this is still an issue.
