### ISSUE TITLE
Current Hit Points are not correctly updated

### ISSUE THREAD

**Issue by g-bauer** [giffyglyph/foundry_5e_monster_maker#3]
When one creates a new monster, the current HP are set to a static value of 10 and that value does not automatically change when e.g. a different `Level` is selected. It's a minor inconvenience but it would be nice if the default current HP would match the maximum HP.

**Comment by giffyglyph** [comment]
I think the fix here is to scale current HP with maximum HP.

**Comment by giffyglyph** [comment]
Tested and verified in v0.5.4-dev. Closing.
