### ISSUE TITLE
Unable to open item sheet

### ISSUE THREAD

**Issue by Tabletop-RPG-Music** [giffyglyph/foundry_5e_monster_maker#5]
After messing around with the module for a little while, the item sheet suddenly won't open. Even the regular dnd5e item sheet won't open as well. Not sure what triggered this. I'll try again in a new world and see if I have the same issue.

**Comment by Tabletop-RPG-Music** [comment]
Tried this again on a new world and immediately after making an item and switching the sheet to your item sheet the item closes and no items can be reopened.

**Comment by giffyglyph** [comment]
I've created a dev branch with a (hopeful) fix: you can test it by uninstalling the live module and switching to the dev manifest:

Manifest: https://raw.githubusercontent.com/giffyglyph/foundry_5e_monster_maker/dev/module.json.

If all goes well, I'll merge this in to live by end-of-day.

**Comment by giffyglyph** [comment]
Tested and verified in v0.5.4-dev. Closing.
