### ISSUE TITLE
Enable usage of monster `Die Size` within `Feature` and `Spell`

### ISSUE THREAD

**Issue by g-bauer** [giffyglyph/foundry_5e_monster_maker#8]
It would be nice to be able to write something like `[damage, dice]` where `dice` is the `Die Size` selected in the `Damage (per Action)` section.

**Comment by giffyglyph** [comment]
The fix here is to add a new shortcode—something like [monsterDamageDie].

**Comment by giffyglyph** [comment]
Tested and verified in v0.5.4-dev. Closing.
